services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    restart: unless-stopped
    networks:
      - sharedApiNetwork


networks:
  sharedApiNetwork:
    external: true